### ISSUE TITLE
home assistant integration

### ISSUE THREAD

**Issue by Videx1** [aglehmann/pyEcovent#8]
Hello, 
i don't know if this is the right place to write for questions, but i didn't find any other place.
I added my blauberg fan to home assistant and i can turn it off and on. I saw that this app allows you to control th speed of the fan and mode. Where do you need to add the code and how to add it to dashboard. Is there any lovelace config? (Im kinda new to home assistant and kinda lost for some things soo please be kind :) also if you have discord please let me know so i can add you and ask you some questions about other stuff in home assistant)

**Comment by aglehmann** [comment]
Hi,
Controlling the fan feed is possible, you can select three different modes (low, medium, high). If you added the fan to lovelace as an 'entity card' then you should be able to select fan speeds by simply clicking the card. Changing the fan mode is also possible but slightly more cumbersome. The custom component ships with a custom service called 'fan.ecovent_set_airflow', which controls the three different modes these fans can operate in; described here:
https://github.com/aglehmann/home_assistant_ecovent/blob/master/info.md
There isn't a lovelace card for these fans because they somewhere between a hvac unit and fan from a home assistant perspective, which means neither built-in card really fit. I haven't made a custom card for it either and probably wont in the near future unfortunately.
